In [44]:
import numpy as np
import pandas as pd

In [45]:
from sklearn.impute import SimpleImputer   
from sklearn.preprocessing import OneHotEncoder # gender,profession
from sklearn.preprocessing import OrdinalEncoder

In [48]:
df = pd.read_csv(r"C:\Users\DELL\Downloads\Customers.csv")

In [49]:
df.head()

,CustomerID,Gender,Age,Annual Income ($),Spending Score (1-100),Profession,Work Experience,Family Size
0,1,Male,19,15000,39,Healthcare,1,4
1,2,Male,21,35000,81,Engineer,3,3
2,3,Female,20,86000,6,Engineer,1,1
3,4,Female,23,59000,77,Lawyer,0,2
4,5,Female,31,38000,40,Entertainment,2,6

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CustomerID              2000 non-null   int64
 1   Gender                  2000 non-null   object
 2   Age                     2000 non-null   int64
 3   Annual Income ($)       2000 non-null   int64
 4   Spending Score (1-100)  2000 non-null   int64
 5   Profession              1965 non-null   object
 6   Work Experience         2000 non-null   int64
 7   Family Size             2000 non-null   int64
dtypes: int64(6), object(2)
memory usage: 125.1+ KB

In [51]:
df.shape

(2000, 8)

In [52]:
df.isnull().sum()

CustomerID                 0
Gender                     0
Age                        0
Annual Income ($)          0
Spending Score (1-100)     0
Profession                35
Work Experience            0
Family Size                0
dtype: int64

In [53]:
df=df.dropna()

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1965 entries, 0 to 1999
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CustomerID              1965 non-null   int64
 1   Gender                  1965 non-null   object
 2   Age                     1965 non-null   int64
 3   Annual Income ($)       1965 non-null   int64
 4   Spending Score (1-100)  1965 non-null   int64
 5   Profession              1965 non-null   object
 6   Work Experience         1965 non-null   int64
 7   Family Size             1965 non-null   int64
dtypes: int64(6), object(2)
memory usage: 138.2+ KB

In [55]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['Family Size']),df['Family Size'],
                                                test_size=0.2)

In [56]:
X_train

,CustomerID,Gender,Age,Annual Income ($),Spending Score (1-100),Profession,Work Experience
971,972,Female,59,108675,57,Artist,4
1335,1336,Female,75,76474,5,Doctor,5
227,228,Male,76,89000,86,Healthcare,9
1275,1276,Male,11,166361,59,Engineer,6
1411,1412,Female,51,58006,83,Executive,1
...,...,...,...,...,...,...,...
573,574,Female,64,59088,31,Artist,1
1774,1775,Female,60,174768,66,Entertainment,9
1551,1552,Male,4,131093,79,Lawyer,1
1056,1057,Male,47,65207,81,Healthcare,1
1853,1854,Male,98,125181,30,Artist,0

In [60]:
# df['Work Experience'].value_counts()

In [57]:
from sklearn.compose import ColumnTransformer

In [62]:
transformer = ColumnTransformer(transformers=[
    # ('tnf1',SimpleImputer(),['fever']), 
    # ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['Gender','Profession'])
],remainder='passthrough')

In [64]:
transformer.fit_transform(X_train).shape

(1572, 14)

In [65]:
transformer.transform(X_test).shape

(393, 14)