In [2]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv(r"C:\Users\DELL\Downloads\used_cars_data.csv")

In [4]:
df.head()

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74

In [5]:
df=df[['Name','Kilometers_Driven','Fuel_Type','Owner_Type','Engine','New_Price']]

In [6]:
df.head()

,Name,Kilometers_Driven,Fuel_Type,Owner_Type,Engine,New_Price
0,Maruti Wagon R LXI CNG,72000,CNG,First,998 CC,NaN
1,Hyundai Creta 1.6 CRDi SX Option,41000,Diesel,First,1582 CC,NaN
2,Honda Jazz V,46000,Petrol,First,1199 CC,8.61 Lakh
3,Maruti Ertiga VDI,87000,Diesel,First,1248 CC,NaN
4,Audi A4 New 2.0 TDI Multitronic,40670,Diesel,Second,1968 CC,NaN

In [30]:
df['Name'].value_counts()

Name
Mahindra XUV500 W8 2WD                  55
Maruti Swift VDI                        49
Maruti Swift Dzire VDI                  42
Honda City 1.5 S MT                     39
Maruti Swift VDI BSIV                   37
                                        ..
Chevrolet Beat LT Option                 1
Skoda Rapid 1.6 MPI AT Elegance Plus     1
Ford EcoSport 1.5 TDCi Ambiente          1
Hyundai i10 Magna 1.1 iTech SE           1
Hyundai Elite i20 Magna Plus             1
Name: count, Length: 2041, dtype: int64

In [31]:
pd.get_dummies(df,columns=['Fuel_Type','Owner_Type'],dtype=int)

,Name,Kilometers_Driven,Engine,New_Price,Fuel_Type_CNG,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_LPG,Fuel_Type_Petrol,Owner_Type_First,Owner_Type_Fourth & Above,Owner_Type_Second,Owner_Type_Third
0,Maruti Wagon R LXI CNG,72000,998 CC,NaN,1,0,0,0,0,1,0,0,0
1,Hyundai Creta 1.6 CRDi SX Option,41000,1582 CC,NaN,0,1,0,0,0,1,0,0,0
2,Honda Jazz V,46000,1199 CC,8.61 Lakh,0,0,0,0,1,1,0,0,0
3,Maruti Ertiga VDI,87000,1248 CC,NaN,0,1,0,0,0,1,0,0,0
4,Audi A4 New 2.0 TDI Multitronic,40670,1968 CC,NaN,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7248,Volkswagen Vento Diesel Trendline,89411,1598 CC,NaN,0,1,0,0,0,1,0,0,0
7249,Volkswagen Polo GT TSI,59000,1197 CC,NaN,0,0,0,0,1,1,0,0,0
7250,Nissan Micra Diesel XV,28000,1461 CC,NaN,0,1,0,0,0,1,0,0,0
7251,Volkswagen Polo GT TSI,52262,1197 CC,NaN,0,0,0,0,1,0,0,0,1
7252,Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...,72443,2148 CC,NaN,0,1,0,0,0,1,0,0,0

In [13]:
pd.get_dummies(df,columns=['Fuel_Type','Owner_Type'],dtype=int,drop_first=True)

,Name,Kilometers_Driven,Engine,New_Price,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_LPG,Fuel_Type_Petrol,Owner_Type_Fourth & Above,Owner_Type_Second,Owner_Type_Third
0,Maruti Wagon R LXI CNG,72000,998 CC,NaN,0,0,0,0,0,0,0
1,Hyundai Creta 1.6 CRDi SX Option,41000,1582 CC,NaN,1,0,0,0,0,0,0
2,Honda Jazz V,46000,1199 CC,8.61 Lakh,0,0,0,1,0,0,0
3,Maruti Ertiga VDI,87000,1248 CC,NaN,1,0,0,0,0,0,0
4,Audi A4 New 2.0 TDI Multitronic,40670,1968 CC,NaN,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...
7248,Volkswagen Vento Diesel Trendline,89411,1598 CC,NaN,1,0,0,0,0,0,0
7249,Volkswagen Polo GT TSI,59000,1197 CC,NaN,0,0,0,1,0,0,0
7250,Nissan Micra Diesel XV,28000,1461 CC,NaN,1,0,0,0,0,0,0
7251,Volkswagen Polo GT TSI,52262,1197 CC,NaN,0,0,0,1,0,0,1
7252,Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...,72443,2148 CC,NaN,1,0,0,0,0,0,0

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2,random_state=2)

In [16]:
X_train.head()

                             Name  Kilometers_Driven Fuel_Type Owner_Type
4470         Honda Amaze S Diesel              46500    Diesel      First
1398    Honda City V MT Exclusive               5377    Petrol      First
4950  Ford Aspire Titanium Diesel              60048    Diesel      First
1279           Honda City 1.5 EXI              98437    Petrol      First
874   Audi A4 2.0 TDI Multitronic              59000    Diesel      First

In [17]:
from sklearn.preprocessing import OneHotEncoder

In [19]:
ohe = OneHotEncoder(drop='first',sparse_output=False,dtype=np.int32)

In [21]:
X_train_new = ohe.fit_transform(X_train[['Fuel_Type','Owner_Type']])

In [22]:
X_test_new = ohe.transform(X_test[['Fuel_Type','Owner_Type']])

In [23]:

X_train_new.shape

(5802, 7)

In [24]:
np.hstack((X_train[['Name','Kilometers_Driven']].values,X_train_new))

array([['Honda Amaze S Diesel', 46500, 1, ..., 0, 0, 0],
       ['Honda City V MT Exclusive', 5377, 0, ..., 0, 0, 0],
       ['Ford Aspire Titanium Diesel', 60048, 1, ..., 0, 0, 0],
       ...,
       ['Volkswagen Ameo 1.5 TDI Comfortline AT', 54455, 1, ..., 0, 0, 0],
       ['Toyota Innova Crysta 2.8 ZX AT', 27270, 1, ..., 0, 0, 0],
       ['Chevrolet Tavera LS B3 10 Seats BSIII', 120000, 1, ..., 0, 0, 0]],
      shape=(5802, 9), dtype=object)

In [26]:
counts = df['Name'].value_counts()

In [41]:
df['Name'].nunique()
threshold = 20

In [42]:
repl = counts[counts <= threshold].index

In [43]:
pd.get_dummies(df['Name'].replace(repl, 'uncommon'),dtype=int).sample(7)

,Audi A4 2.0 TDI,BMW 3 Series 320d,Honda Amaze S i-Dtech,Honda Amaze S i-Vtech,Honda Brio S MT,Honda City 1.5 S MT,Honda City 1.5 V MT,Hyundai Creta 1.6 CRDi SX,Hyundai EON Era Plus,Hyundai Grand i10 Sportz,...,Maruti Swift VDI,Maruti Swift VDI BSIV,Maruti Wagon R LXI,Maruti Wagon R VXI,Skoda Superb Elegance 1.8 TSI AT,Toyota Fortuner 3.0 Diesel,Toyota Fortuner 4x2 AT,Volkswagen Polo 1.2 MPI Highline,Volkswagen Vento Diesel Highline,uncommon
4891,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
6493,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2601,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5458,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
6679,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
6811,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
7215,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1